import React, { ReactNode } from 'react';
import {
  Agriculture,
  Assessment,
  AssignmentTurnedIn,
  CheckCircle,
  Construction,
  Dashboard,
  Description,
  Edit,
  EditNote,
  FolderOutlined,
  HomeWork,
  Info,
  Insights,
  Inventory,
  ListAlt,
  LocalHospital,
  Notifications,
  People,
  Pets,
  RiceBowl,
  Settings,
  ShoppingCart,
  Timeline,
  Storage,
  StorageOutlined,
  CategoryOutlined,
} from '@mui/icons-material';

export const MENU_ICON_KEYS = [
  'dashboard',
  'record',
  'farm',
  'pigStock',
  'feeding',
  'health',
  'openHouse',
  'warehouse',
  'purchase',
  'construction',
  'reportCenter',
  'approval',
  'analytics',
  'notification',
  'users',
  'masterData',
  'documents',
  'settings',
  'shoppingBag',
  'list',
  'shoppingCart',
  'assignment',
  'edit',
  'reports',
  'insights',
  'notifications',
  'checkCircle',
  'info',
  'database',
  'folder',
] as const;

export type MenuIconKey = (typeof MENU_ICON_KEYS)[number];

export const MENU_ICONS: Record<MenuIconKey, ReactNode> = {
  dashboard: <Dashboard />,
  record: <EditNote />,
  farm: <Agriculture />,
  pigStock: <Pets />,
  feeding: <RiceBowl />,
  health: <LocalHospital />,
  openHouse: <HomeWork />,
  warehouse: <Inventory />,
  purchase: <ShoppingCart />,
  construction: <Construction />,
  reportCenter: <Assessment />,
  approval: <AssignmentTurnedIn />,
  analytics: <Timeline />,
  notification: <Notifications />,
  users: <People />,
  masterData: <Storage />,
  documents: <Description />,
  settings: <Settings />,
  shoppingBag: <CategoryOutlined />,
  list: <ListAlt />,
  // DB icon_key aliases
  shoppingCart: <ShoppingCart />,
  assignment: <AssignmentTurnedIn />,
  edit: <Edit />,
  reports: <Assessment />,
  insights: <Insights />,
  notifications: <Notifications />,
  checkCircle: <CheckCircle />,
  info: <Info />,
  database: <StorageOutlined />,
  folder: <Description />,
};

export function resolveMenuIcon(iconKey: string | undefined): ReactNode {
  if (!iconKey) return <Dashboard sx={{ fontSize: 'inherit' }} />;
  const icon = MENU_ICONS[iconKey as MenuIconKey];
  return icon ?? <FolderOutlined sx={{ fontSize: 'inherit' }} />;
}
